### PR TITLE
Make async-looking functions actually async.

### PR DESCRIPTION
**Pull request by Jovascript**
Wrap with process.nextTick()

### CODE REVIEW

**Comment by goloroden** [comment]
Great, thanks a lot for your PR 😊 

Before I am going to merge it – would you like to add yourself to the list of contributors in the `package.json` file and add this change to this PR?

**Comment by goloroden** [comment]
Thanks a lot 😊

Is it okay if I publish within the next days, or do you need the updated version immediately?

**Comment by goloroden** [comment]
PS: Okay, forget my question… new version has been deployed to npm: `0.3.2`

**Comment by Jovascript** [comment]
Great, happy to help :smile:

**Pull request merged**
